// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GqlInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param string `protobuf:"bytes,50031,opt,name=param,proto3" json:"param,omitempty"`
	Type  string `protobuf:"bytes,50032,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GqlInput) Reset() {
	*x = GqlInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GqlInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GqlInput) ProtoMessage() {}

func (x *GqlInput) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GqlInput.ProtoReflect.Descriptor instead.
func (*GqlInput) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *GqlInput) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *GqlInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      string    `protobuf:"bytes,50001,opt,name=kind,proto3" json:"kind,omitempty"`
	Target    uint32    `protobuf:"varint,50002,opt,name=target,proto3" json:"target,omitempty"` // 0, 1, 2, 3
	GqlInput  *GqlInput `protobuf:"bytes,50003,opt,name=gql_input,json=gqlInput,proto3" json:"gql_input,omitempty"`
	GqlOutput string    `protobuf:"bytes,50004,opt,name=gql_output,json=gqlOutput,proto3" json:"gql_output,omitempty"`
	Skip      bool      `protobuf:"varint,50005,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MethodOptions) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *MethodOptions) GetGqlInput() *GqlInput {
	if x != nil {
		return x.GqlInput
	}
	return nil
}

func (x *MethodOptions) GetGqlOutput() string {
	if x != nil {
		return x.GqlOutput
	}
	return ""
}

func (x *MethodOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

var file_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         50000,
		Name:          "protoc_graphql.method",
		Tag:           "bytes,50000,opt,name=method",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50011,
		Name:          "protoc_graphql.skip",
		Tag:           "varint,50011,opt,name=skip",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50021,
		Name:          "protoc_graphql.required",
		Tag:           "varint,50021,opt,name=required",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50022,
		Name:          "protoc_graphql.keep_case",
		Tag:           "varint,50022,opt,name=keep_case",
		Filename:      "options/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional protoc_graphql.MethodOptions method = 50000;
	E_Method = &file_options_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool skip = 50011;
	E_Skip = &file_options_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool required = 50021;
	E_Required = &file_options_options_proto_extTypes[2]
	// optional bool keep_case = 50022;
	E_KeepCase = &file_options_options_proto_extTypes[3]
)

var File_options_options_proto protoreflect.FileDescriptor

var file_options_options_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x08, 0x47, 0x71, 0x6c,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0xef,
	0x86, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0xf0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0xd1, 0x86,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x71, 0x6c, 0x5f, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0xd3, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x71, 0x6c, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x08, 0x67, 0x71, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f,
	0x0a, 0x0a, 0x67, 0x71, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0xd4, 0x86, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x71, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0xd5, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x3a, 0x57, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x35,
	0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xdb, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x3a, 0x3e, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xe5, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x3a, 0x3f, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x63, 0x61,
	0x73, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xe6, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65, 0x65, 0x70, 0x43,
	0x61, 0x73, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData = file_options_options_proto_rawDesc
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_options_options_proto_rawDescData)
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_options_options_proto_goTypes = []any{
	(*GqlInput)(nil),                    // 0: protoc_graphql.GqlInput
	(*MethodOptions)(nil),               // 1: protoc_graphql.MethodOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_options_options_proto_depIdxs = []int32{
	0, // 0: protoc_graphql.MethodOptions.gql_input:type_name -> protoc_graphql.GqlInput
	2, // 1: protoc_graphql.method:extendee -> google.protobuf.MethodOptions
	3, // 2: protoc_graphql.skip:extendee -> google.protobuf.MessageOptions
	4, // 3: protoc_graphql.required:extendee -> google.protobuf.FieldOptions
	4, // 4: protoc_graphql.keep_case:extendee -> google.protobuf.FieldOptions
	1, // 5: protoc_graphql.method:type_name -> protoc_graphql.MethodOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	1, // [1:5] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_options_options_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GqlInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_options_options_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_options_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		MessageInfos:      file_options_options_proto_msgTypes,
		ExtensionInfos:    file_options_options_proto_extTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_rawDesc = nil
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
