package internal

import (
	"google.golang.org/protobuf/types/pluginpb"
)

// Write the header content
func (schema *Schema) WriteHeader() {
	schema.NewLine()
	schema.Comment("Auto-generated by protoc-gen-graphql. DO NOT EDIT\n")
	schema.Comment(NAME + " " + VERSION)
	schema.NewLine()
}

// String stores v in a new string value and returns a pointer to it.
func String(v string) *string {
	return &v
}

// Generates the protoc response
func (plugin *Plugin) Execute() {
	for _, protoFile := range plugin.Request.ProtoFile {
		schema := NewSchema()
		fileName := schema.FileName(protoFile.Name)

		plugin.Response.File = append(plugin.Response.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    String(fileName),
			Content: String(schema.String()),
		})
		plugin.schema = append(plugin.schema, schema)
	}
}
