package internal

import (
	"google.golang.org/protobuf/types/pluginpb"
)

// Write the header content
func (p *Plugin) WriteHeader() {
	p.schema.NewLine()
	p.schema.Comment("Auto-generated by protoc-gen-graphql. DO NOT EDIT\n")
	p.schema.Comment("protoc-gen-graphql v0.1")
	p.schema.NewLine()
}

// String stores v in a new string value and returns a pointer to it.
func String(v string) *string { return &v }

// Generates the protoc response
func (p *Plugin) Generate() {
	p.WriteHeader()

	p.Response.File = append(p.Response.File, &pluginpb.CodeGeneratorResponse_File{
		Name:    String("schema.graphql"),
		Content: String(p.schema.String()),
	})
}
